spring.application.name=desafio
spring.config.import=optional:file:.env[.properties]
# ========== Configuração do MySQL ==========
# Substitua "nome_do_seu_banco" pelo nome do schema criado no MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========== Configuração do JPA / Hibernate ==========
# update: Cria as tabelas se não existirem e atualiza a estrutura sem apagar dados existentes
spring.jpa.hibernate.ddl-auto=update

# Exibe as consultas SQL geradas pelo Hibernate no console
spring.jpa.show-sql=true

# Formata o SQL exibido no console para facilitar a leitura
spring.jpa.properties.hibernate.format_sql=true

# Define o dialeto correto para otimizar as consultas para o MySQL 8+
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
